#!/usr/bin/env python3
"""gen_database_doc.py -- write BOATS_DATABASE.md from boats_db.lua and
data/boats_sources.json. Generated so the document cannot disagree with the
data it describes. Run from the module root."""
import json
import math
import os
import subprocess
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
DB = json.loads(subprocess.run([sys.executable, '-I', 'tools/luarun.py', 'tools/dump_db.lua'],
                               cwd=ROOT, capture_output=True, text=True, check=True).stdout)
SRC = json.load(open(os.path.join(ROOT, 'data', 'boats_sources.json')))

out = []
w = out.append


def num(x, nd=1):
    if x is None:
        return '—'
    if isinstance(x, (int, float)):
        s = ('%.' + str(nd) + 'f') % x
        return s.rstrip('0').rstrip('.') if '.' in s else s
    return str(x)


def deg(rad):
    return num(math.degrees(rad), 1)


w('# WhyWalk Boats — movement database')
w('')
w('Generated by `tools/gen_database_doc.py` from `scripts/WhyWalk/Boats/boats_db.lua` and')
w('`data/boats_sources.json` (itself extracted from the reference mods by')
w('`tools/build_boats_sources.py`). Edit those, not this file.')
w('')
w('Units: world units (u), seconds, radians; degrees shown alongside where they help.')
w('Vessel frame: x to starboard, y toward the bow, z up.')
w('')

# ---------------------------------------------------------------- runtime vessels
w('## 1. Vessels the module sails')
w('')
w('| Vessel | Top ahead | Astern | Accel | Brake | Drag | Turn | Pivot | Response | Water offset | Pose | Sound |')
w('|---|---|---|---|---|---|---|---|---|---|---|---|')
for vid in sorted(DB['VESSELS']):
    v = DB['VESSELS'][vid]
    w('| **%s** `%s` | %s u/s | %s u/s | %s u/s² | %s u/s² | %s /s | %s rad/s (%s°/s) | %s | %s /s | %s u | %s | %s |' % (
        v['name'], vid, num(v['maxSpeed']), num(v['reverseSpeed']), num(v['accel']), num(v['brake']),
        num(v['drag'], 3), num(v['turnRate'], 4), deg(v['turnRate']), num(v['pivot'], 2),
        num(v['turnResponse']), num(v['waterOffset']), v['pose'], v.get('sound') or '—'))
w('')
w('Time to top speed is `maxSpeed / accel`; coasting halves speed every `ln 2 / drag` '
  '(1.15 s at the shared 0.603). The pilot\'s own run speed caps the top speed actually reached.')
w('')
w('### Stations and hulls')
w('')
w('| Vessel | Pilot anchor (x, y, z) | Bow | Stern | Half beam | Draft |')
w('|---|---|---|---|---|---|')
for vid in sorted(DB['VESSELS']):
    v = DB['VESSELS'][vid]
    a = v['anchor']
    h = v.get('hull')
    hull = ('%s | %s | %s | %s' % (num(h['bow']), num(h['stern']), num(h['halfBeam']), num(h['draft']))) if h \
        else 'measured from the bounding box on first boarding | | |'
    w('| %s | (%s, %s, %s) | %s |' % (vid, num(a['x']), num(a['y']), num(a['z']), hull))
w('')
w('### Motion (cosmetic)')
w('')
w('| Vessel | Roll | Roll freq | Heel max | Heel rate | Pitch | Pitch period |')
w('|---|---|---|---|---|---|---|')
for vid in sorted(DB['VESSELS']):
    m = DB['VESSELS'][vid]['motion']
    w('| %s | %s rad (%s°) | %s Hz | %s rad | %s rad/s | %s rad (%s°) | %s s |' % (
        vid, num(m['roll'], 4), deg(m['roll']), num(m['rollFreq'], 2), num(m['heelMax'], 3),
        num(m['heelRate'], 4), num(m['pitch'], 4), deg(m['pitch']), num(m['pitchPeriod'])))
w('')

# ---------------------------------------------------------------- provenance
w('## 2. Where every number comes from')
w('')
w('`src:` entries are checked against the extracted sources by `tools/check_db_sources.py`;')
w('a drifted value fails the build. `derived:` and `pref:` are judgements, shown for review.')
w('')
for vid in sorted(DB['PROVENANCE']):
    w('**%s**' % vid)
    w('')
    for field in sorted(DB['PROVENANCE'][vid]):
        w('- `%s` — %s' % (field, DB['PROVENANCE'][vid][field]))
    w('')

# ---------------------------------------------------------------- models and records
w('## 3. Meshes and records')
w('')
w('| Mesh (normalised) | Vessel | Bow axis | Origin in vessel frame |')
w('|---|---|---|---|')
for key in sorted(DB['MODELS']):
    e = DB['MODELS'][key]
    axis = '+Y' if abs(e['yawOffset']) < 1e-6 else '−Y (yawOffset π)'
    o = e.get('origin')
    w('| `%s` | %s | %s | %s |' % (key, e['vessel'], axis,
                                    '(%s, %s, %s)' % (num(o['x']), num(o['y']), num(o['z'])) if o else 'vessel origin'))
w('')
w('| Record | Taken over | Why |')
w('|---|---|---|')
for rid in sorted(DB['RECORDS']):
    r = DB['RECORDS'][rid]
    w('| `%s` | %s | %s |' % (rid, 'yes' if r['claim'] else 'no', r['reason']))
w('')

# ---------------------------------------------------------------- sources: IT
it = SRC['immersiveTravel']
w('## 4. Source catalogue')
w('')
w('### Immersive Travel (rfuzzo), OpenMW shim — %d fps basis' % it['fps'])
w('')
w('`speed` is units per tick, scaled `speed * dt * 60`; `turnspeed / 10000` radians per tick; '
  'sway amplitude `sway * %s` rad at %s Hz, up to %s× in a turn.' % (
      it['sway']['SWAY_AMPL']['raw'], it['sway']['SWAY_FREQ']['raw'], it['sway']['SWAY_MAX_AMPL']['raw']))
w('')
w('| Mount | Mesh | Speed | Turn | Sway | Offset | Free movement | Slots | Guide slot |')
w('|---|---|---|---|---|---|---|---|---|')
for mid in sorted(it['mounts']):
    m = it['mounts'][mid]
    g = m.get('guideSlot') or {}
    w('| `%s` | `%s` | %s u/s | %s rad/s (%s°/s) | %s rad | %s | %s | %d | (%s, %s, %s) |' % (
        mid, m.get('mesh') or '—', num(m['speed']['value']), num(m['turnRate']['value'], 4),
        deg(m['turnRate']['value']), num(m['swayAmplitude']['value'], 3), num(m['waterOffset']['value']),
        'yes' if m.get('hasFreeMovement') else 'no', len(m['slots']),
        num(g.get('x')), num(g.get('y')), num(g.get('z'))))
w('')
w('Routes: ' + '; '.join('%s %d routes / %d points%s' % (
    k, v['routes'], v['points'], (' (empty: %s)' % ', '.join(v['emptyRoutes'])) if v['emptyRoutes'] else '')
    for k, v in sorted(it['routes'].items())) + '.')
w('')

# ---------------------------------------------------------------- Stormrider
sr = SRC['stormrider']
w('### Stormrider Expanded — speedf × %s = u/s' % num(sr['globals']['SpeedFPSMod']))
w('')
w('| Ship | Mesh | Base (no wind) | Limit (full wind) | Accel | Decel | Turn | Boat z | Pilot seat |')
w('|---|---|---|---|---|---|---|---|---|')
for key in sorted(sr['ships']):
    s = sr['ships'][key]
    turn = s.get('turnRate') or s.get('turnRatePerSpeed')
    turn_txt = '—'
    if turn:
        turn_txt = '%s rad/s' % num(turn['value'], 4) if 'turnRate' in s else '%s rad/s per speedf' % num(turn['value'], 4)
    seat = (s.get('pilotSeat') or {}).get('raw') or {}
    w('| %s `%s` | `%s` | %s | %s | %s | %s | %s | %s | %s |' % (
        s.get('name'), key, s.get('mesh'),
        num((s.get('baseSpeed') or {}).get('value')), num((s.get('speedLimit') or {}).get('value')),
        num((s.get('accel') or {}).get('value')), num((s.get('decel') or {}).get('value')), turn_txt,
        num((s.get('waterOffset') or {}).get('value')),
        '(%s, %s, %s)' % (num(seat.get('x')), num(seat.get('y')), num(seat.get('z'))) if seat else '—'))
w('')
for n in sr['globals']['notes']:
    w('- ' + n)
w('')


def constants(title, node, notes_key='notes'):
    w('### ' + title)
    w('')
    w('| Constant | Raw | Canonical | Formula | Line |')
    w('|---|---|---|---|---|')
    for k, v in node.items():
        if not isinstance(v, dict) or 'value' not in v:
            continue
        w('| %s | %s %s | %s %s | %s | %s |' % (k, num(v['raw'], 4), v['unit'], num(v['value'], 4),
                                               v['canonicalUnit'], v['formula'], v.get('line', '')))
    w('')
    for n in node.get(notes_key, []):
        w('- ' + n)
    w('')


constants("Ben's Skyships (the gold standard) — 80 fps basis", SRC['skyships'])
constants("Aetherius's Outpost (reference) — 60 fps basis", SRC['aetheriusOutpost'])
constants('Rideable Silt Striders (Ben) — 60 fps basis', SRC['rideableSiltStriders'])
constants('Your Own Gondola (GrumblingVomit)', SRC['yourOwnGondola'])

# ---------------------------------------------------------------- meshes
w('## 5. Mesh measurements')
w('')
w('Read from the NIF geometry by `tools/nifbox.py`, in each mesh\'s own frame. The collision box is the')
w('RootCollisionNode geometry, which is what the hull values above use.')
w('')
w('| Mesh | Source | Bow | Render min | Render max | Collision min | Collision max |')
w('|---|---|---|---|---|---|---|')
for key in sorted(SRC['meshes']):
    m = SRC['meshes'][key]
    c = m.get('collision') or {}
    w('| `%s` | %s | %s | %s | %s | %s | %s |' % (key, m['source'], m['bowAxis'], m['render']['min'],
                                                m['render']['max'], c.get('min', '—'), c.get('max', '—')))
w('')
for key in sorted(SRC['meshes']):
    m = SRC['meshes'][key]
    w('- `%s`: bow %s — %s.%s' % (key, m['bowAxis'], m['bowEvidence'],
                                 (' ' + m['note']) if m.get('note') else ''))
w('')

if SRC.get('dataDefects'):
    w('## 6. Defects found in the source data')
    w('')
    for d in SRC['dataDefects']:
        w('- `%s`: %s — %s.' % (d['file'], d['error'], d['impact']))
    w('')

open(os.path.join(ROOT, 'BOATS_DATABASE.md'), 'w').write('\n'.join(out))
print('wrote BOATS_DATABASE.md (%d lines)' % len(out))
